language: php
sudo: false

env:
  global:
    - COMPOSER_DISABLE_XDEBUG_WARN=1

matrix:
  include:
    - php: 7.1
      env: CODESTYLE="yes"

script:
  # Run PHPUnit if we're not checking code style, otherwise run phpcs
  - if [[ $CODESTYLE != "yes" ]]; then composer test; else composer phpcs; fi

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email: false
